---
title: "ge and credits"
author: "JP"
date: "3/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
library(plotly)
library(reactable)

theme_set(theme_classic())

wide <- read_csv('C:/Users/cpppe/Desktop/github_projects/gradschool_dashboard/data/wide_data.csv') %>% 
  filter(year == 18) %>% 
  dplyr::select(-X1)

wide <- wide %>% 
  mutate(credit_per_class = credit/headcount,
         credit_per_full_num = case_when(credit_per_class < 2 ~ 1,
                                      credit_per_class >= 2 & credit_per_class < 3 ~ 2,
                                      credit_per_class >= 3 & credit_per_class < 4 ~ 3,
                                      credit_per_class >= 4 & credit_per_class < 5 ~ 4,
                                      credit_per_class >= 5 & credit_per_class < 6 ~ 5,
                                      credit_per_class >= 6 & credit_per_class < 7 ~ 6,
                                      credit_per_class >= 7 & credit_per_class < 8 ~ 7,
                                      credit_per_class >= 8 & credit_per_class < 9 ~ 8,
                                      credit_per_class >= 9 & credit_per_class < 10 ~ 9,
                                      credit_per_class >= 10 & credit_per_class < 11 ~ 10,
                                      credit_per_class >= 11 & credit_per_class < 12 ~ 11,
                                      credit_per_class >= 12 & credit_per_class < 13 ~ 12,
                                      credit_per_class >= 13 & credit_per_class < 14 ~ 13,
                                      credit_per_class >= 14 & credit_per_class < 15 ~ 14,
                                      credit_per_class == 15 ~ 15)) %>% 
  filter(course_level == 'Undergraduate')

wide <- wide %>% 
  sample_frac(.05)
```

```{r}
wide %>% 
  filter(college == 'College of Arts & Sciences' &
           ge_teach_fte < .5) %>% 
  drop_na(ge_teach_fte, credit) %>% 
  ggplot(aes(ge_teach_fte, credit)) +
  geom_point(aes(color = as.factor(course_dept)), alpha = .7) +
  geom_smooth(aes(color = as.factor(course_dept)), method = 'lm', se = FALSE) +
  theme(legend.position = 'none') +
  scale_color_manual(values = c('#5e2228', '#d22a2c', '#9b2a30', '#c80010',
                     '#6a1f25', '#d72d2b', '#5b2c2f', '#387448',
                     '#c0c5ba', '#888980', '#344039', '#4f4c3c',
                     '#807f67', '#386350', '#387448', '#5b6242',
                     '#669b3e', '#808572', '#7fb7b7', '#53636b',
                     '#85b3c1', '#507b8b', '#2c6195', '#4b5f71',
                     '#4b5f71', '#3f6698', '#26657f', '#398b98',
                     '#ddca72', '#c3b37d', '#d3bb95', '#c4bb9b',
                     '#a26540',
                     '#dbd5a5', '#a86428', '#c7a860', '#c0cc56', 
                     '#e5e1d4', '#d3bb95', '#a26540', '#ead568',
                     '#7f5d47', '#b23a2d', '#c33431', 'd74122',
                     '#b23a2d'))

wide %>% 
  filter(college == 'College of Design' &
           ge_teach_fte < .5) %>% 
  drop_na(ge_teach_fte, credit) %>% 
  ggplot(aes(ge_teach_fte, credit)) +
  geom_point(aes(color = as.factor(course_dept)), alpha = .7) +
  geom_smooth(aes(color = as.factor(course_dept)), method = 'lm', se = FALSE) +
  theme(legend.title = element_blank())

wide %>% 
  filter(college == 'College of Education' &
           ge_teach_fte < .5) %>% 
  drop_na(ge_teach_fte, credit) %>% 
  ggplot(aes(ge_teach_fte, credit)) +
  geom_point(aes(color = as.factor(course_dept)), alpha = .5) +
  geom_smooth(aes(color = as.factor(course_dept)), method = 'lm', se = FALSE) +
  theme(legend.title = element_blank())

wide %>% 
  filter(college == 'Lundquist College of Business' &
           ge_teach_fte < .5) %>% 
  drop_na(ge_teach_fte, credit) %>% 
  ggplot(aes(ge_teach_fte, credit)) +
  geom_point(aes(color = as.factor(course_dept)), alpha = .5) +
  geom_smooth(aes(color = as.factor(course_dept)), method = 'lm', se = FALSE) +
  scale_color_manual(values = c('#398b98')) +
  theme(legend.title = element_blank())

wide %>% 
  filter(college == 'School of Journalism & Communication' &
           ge_teach_fte < .5) %>% 
  drop_na(ge_teach_fte, credit) %>% 
  ggplot(aes(ge_teach_fte, credit)) +
  geom_point(aes(color = as.factor(course_dept)), alpha = .5) +
  geom_smooth(aes(color = as.factor(course_dept)), method = 'lm', se = FALSE) +
  scale_color_manual(values = c('#398b98')) +
  theme(legend.title = element_blank())

wide %>% 
  filter(college == 'School of Law' &
           ge_teach_fte < .5) %>% 
  drop_na(ge_teach_fte, credit) %>% 
  ggplot(aes(ge_teach_fte, credit)) +
  geom_point(aes(color = as.factor(course_dept)), alpha = .5) +
  geom_smooth(aes(color = as.factor(course_dept)), method = 'lm', se = FALSE) +
  scale_color_manual(values = c('#398b98')) +
  theme(legend.title = element_blank())

wide %>% 
  filter(college == 'School of Music & Dance' &
           ge_teach_fte < .5) %>% 
  drop_na(ge_teach_fte, credit) %>% 
  ggplot(aes(ge_teach_fte, credit)) +
  geom_point(aes(color = as.factor(course_dept)), alpha = .5) +
  geom_smooth(aes(color = as.factor(course_dept)), method = 'lm', se = FALSE) +
  scale_color_manual(values = c('#398b98')) +
  theme(legend.title = element_blank())

```

```{r}
beta_func <- function (object){
    if (!"lm" %in% attr(object, "class")) 
        stop("object has to be of class lm")
    object$standardized.coefficients <- coef(object) * apply(as.matrix(model.matrix(object)), 
        2, function(x) sqrt(sum((x - mean(x, na.rm = T) * attr(attr(object$model, 
            "terms"), "intercept"))^2, na.rm = T)))/apply(as.matrix(model.frame(object)[, 
        1]), 2, function(x) sqrt(sum((x - mean(x, na.rm = T) * 
        attr(attr(object$model, "terms"), "intercept"))^2, 
        na.rm = T)))
    # attr(object, "class") <- c("lm.beta", "lm")
    return(object)
}

wide_lm_list <- wide %>% 
  drop_na(college, course_dept, credit, ge_teach_fte) %>% 
  group_by(college, course_dept) %>% 
  nest() %>% 
  mutate(lm_model = map(data, ~lm(credit ~ ge_teach_fte, data = .x)),
         lm_coefs = map(lm_model, coef),
         ge_teach_fte_b = map_dbl(lm_coefs, 2),
         betas = map_dbl(lm_model, ~beta_func(.x)$standardized.coefficients[2]),
         lm_r2 = map_dbl(lm_model, ~summary(.x)$r.squared),
         lm_pvalue = map_dbl(lm_model, ~summary(.x)$coefficients[, 4]['ge_teach_fte']),
         lm_r = map_dbl(lm_r2, ~sqrt(.x)))

wide_lm_list %>% 
  dplyr::select(college, course_dept, ge_teach_fte_b, betas, lm_pvalue) %>% 
  rename(`College` = college,
         `Course Department` = course_dept) %>% 
  mutate(b = round(ge_teach_fte_b, digits = 3),
         beta = round(betas, digits = 3), 
         `p value` = round(lm_pvalue, digits = 3)) %>% 
  dplyr::select(-ge_teach_fte_b, -lm_pvalue, -betas) %>% 
  reactable::reactable()
```

